# You may chosse to overide the current version of Tweego or use another story format than SugarCube, just change it below

[tweego.binaries]
version = 'v2.1.1'

[tweego.binaries.win32]
x86 = 'https://github.com/tmedwards/tweego/releases/download/v2.1.1/tweego-2.1.1-windows-x86.zip'
x64 = 'https://github.com/tmedwards/tweego/releases/download/v2.1.1/tweego-2.1.1-windows-x64.zip'

[tweego.binaries.dawin]
x86 = 'https://github.com/tmedwards/tweego/releases/download/v2.1.1/tweego-2.1.1-macos-x86.zip'
x64 = 'https://github.com/tmedwards/tweego/releases/download/v2.1.1/tweego-2.1.1-macos-x64.zip'

[tweego.binaries.linux]
x86 = 'https://github.com/tmedwards/tweego/releases/download/v2.1.1/tweego-2.1.1-linux-x86.zip'
x64 = 'https://github.com/tmedwards/tweego/releases/download/v2.1.1/tweego-2.1.1-linux-x64.zip'

[storyFormats.sugarcube]
version = 'v2.36.1'
link = 'https://github.com/tmedwards/sugarcube-2/releases/download/v2.36.1/sugarcube-2.36.1-for-twine-2.1-local.zip'
